// In-Memory Database Fallback Store for Development Mode
const bcrypt = require('bcryptjs');

const mockStore = {
  users: [
    {
      _id: '64f1a2b3c4d5e6f7a8b9c0d1',
      name: 'SwadGhar Admin',
      email: 'admin@swadghar.com',
      passwordHash: '$2a$10$wO3bS9R8J7C8gqH8yDqSSe3X4p6V7A9C2m1P3L4k5J6H7G8F9E0D1', // Admin@123
      phone: '+91 98980 12345',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      addresses: [{ _id: 'addr1', street: 'Admin Quarters', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015', isDefault: true }],
      isBlocked: false,
      createdAt: new Date(),
    },
    {
      _id: '64f1a2b3c4d5e6f7a8b9c0d2',
      name: 'Ramesh Patel (Staff)',
      email: 'staff@swadghar.com',
      passwordHash: '$2a$10$wO3bS9R8J7C8gqH8yDqSSe3X4p6V7A9C2m1P3L4k5J6H7G8F9E0D1', // Staff@123
      phone: '+91 98765 11223',
      role: 'staff',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      addresses: [],
      isBlocked: false,
      createdAt: new Date(),
    },
    {
      _id: '64f1a2b3c4d5e6f7a8b9c0d3',
      name: 'Aarav Sharma',
      email: 'customer@gmail.com',
      passwordHash: '$2a$10$wO3bS9R8J7C8gqH8yDqSSe3X4p6V7A9C2m1P3L4k5J6H7G8F9E0D1', // Customer@123
      phone: '+91 98220 55443',
      role: 'customer',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      addresses: [{ _id: 'addr2', street: 'Flat 402, Shivalik High Street', city: 'Ahmedabad', state: 'Gujarat', pincode: '380054', landmark: 'Opposite Central Park', isDefault: true }],
      isBlocked: false,
      createdAt: new Date(),
    },
  ],

  categories: [
    // 15 Gujarati Categories
    { _id: 'cat_guj_1', name: 'Gujarati Snacks', slug: 'gujarati-snacks', description: 'Crispy, light, and mouthwatering afternoon Gujarati snacks.', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', sortOrder: 1, isActive: true },
    { _id: 'cat_guj_2', name: 'Gujarati Breakfast', slug: 'gujarati-breakfast', description: 'Authentic wholesome Gujarati morning specials.', image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80', sortOrder: 2, isActive: true },
    { _id: 'cat_guj_3', name: 'Gujarati Farsan', slug: 'gujarati-farsan', description: 'Famous Gujarati steamed, fried, and baked savory farsaans.', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', sortOrder: 3, isActive: true },
    { _id: 'cat_guj_4', name: 'Gujarati Thali', slug: 'gujarati-thali', description: 'Royal, balanced, and traditional unlimited Gujarati thali platters.', image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80', sortOrder: 4, isActive: true },
    { _id: 'cat_guj_5', name: 'Kathiyawadi Special', slug: 'kathiyawadi-special', description: 'Spicy, rustic Saurashtra and Kathiyawad heritage recipes.', image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80', sortOrder: 5, isActive: true },
    { _id: 'cat_guj_6', name: 'Gujarati Shaak', slug: 'gujarati-shaak', description: 'Traditional Gujarati sweet and savory vegetable curries.', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', sortOrder: 6, isActive: true },
    { _id: 'cat_guj_7', name: 'Gujarati Dal & Kadhi', slug: 'gujarati-dal-kadhi', description: 'Sweet, tangy, and aromatic slow-simmered toor dal and kadhi.', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', sortOrder: 7, isActive: true },
    { _id: 'cat_guj_8', name: 'Gujarati Khichdi', slug: 'gujarati-khichdi', description: 'Wholesome, comforting moong dal and rice khichdi.', image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80', sortOrder: 8, isActive: true },
    { _id: 'cat_guj_9', name: 'Gujarati Roti & Rotla', slug: 'gujarati-roti-rotla', description: 'Soft ghee phulkas, bhakris, and pearl millet rotlas.', image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80', sortOrder: 9, isActive: true },
    { _id: 'cat_guj_10', name: 'Gujarati Rice & Pulao', slug: 'gujarati-rice-pulao', description: 'Fragrant steamed Basmati rice and vegetable pulaos.', image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80', sortOrder: 10, isActive: true },
    { _id: 'cat_guj_11', name: 'Gujarati Combos', slug: 'gujarati-combos', description: 'Convenient and value-packed Gujarati meal combinations.', image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80', sortOrder: 11, isActive: true },
    { _id: 'cat_guj_12', name: 'Gujarati Sweets', slug: 'gujarati-sweets', description: 'Pure desi ghee traditional mithais, Mohanthal, and Sukhdi.', image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', sortOrder: 12, isActive: true },
    { _id: 'cat_guj_13', name: 'Gujarati Desserts', slug: 'gujarati-desserts', description: 'Creamy Shrikhand, Basundi, Doodhpak, and Ghevar.', image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', sortOrder: 13, isActive: true },
    { _id: 'cat_guj_14', name: 'Gujarati Beverages', slug: 'gujarati-beverages', description: 'Cooling spiced buttermilk (Chaas) and fresh coolers.', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', sortOrder: 14, isActive: true },
    { _id: 'cat_guj_15', name: 'Gujarati Pickles & Chutneys', slug: 'gujarati-pickles-chutneys', description: 'Spicy garlic chutney, mango chunda, and fried green chilies.', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', sortOrder: 15, isActive: true },

    // 16 Punjabi Categories
    { _id: 'cat_pun_16', name: 'Punjabi Starters', slug: 'punjabi-starters', description: 'Tandoori platters, kebabs, and crispy North Indian appetizers.', image: 'https://images.unsplash.com/photo-1567184109411-b28f2700e1e5?auto=format&fit=crop&w=600&q=80', sortOrder: 16, isActive: true },
    { _id: 'cat_pun_17', name: 'Punjabi Snacks', slug: 'punjabi-snacks', description: 'Hot Punjabi samosas, aloo tikki chaat, and pakoras.', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', sortOrder: 17, isActive: true },
    { _id: 'cat_pun_18', name: 'Punjabi Breakfast', slug: 'punjabi-breakfast', description: 'Amritsari Kulcha, Chole Bhature, and butter parathas.', image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80', sortOrder: 18, isActive: true },
    { _id: 'cat_pun_19', name: 'Paneer Specials', slug: 'paneer-specials', description: 'Royal cottage cheese delicacies in buttery makhani gravy.', image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80', sortOrder: 19, isActive: true },
    { _id: 'cat_pun_20', name: 'Punjabi Veg Main Course', slug: 'punjabi-veg-main-course', description: 'Classic North Indian dhaba gravies, Sarson Ka Saag, and Kofta.', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', sortOrder: 20, isActive: true },
    { _id: 'cat_pun_21', name: 'Punjabi Dal', slug: 'punjabi-dal', description: 'Rich overnight slow-simmered Dal Makhani and Dal Tadka.', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', sortOrder: 21, isActive: true },
    { _id: 'cat_pun_22', name: 'Punjabi Chole & Rajma', slug: 'punjabi-chole-rajma', description: 'Dark spiced Amritsari Chole and hearty Punjabi Rajma.', image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80', sortOrder: 22, isActive: true },
    { _id: 'cat_pun_23', name: 'Punjabi Rice & Biryani', slug: 'punjabi-rice-biryani', description: 'Royal Dum Biryani, Jeera Rice, and Veg Pulao.', image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80', sortOrder: 23, isActive: true },
    { _id: 'cat_pun_24', name: 'Punjabi Breads', slug: 'punjabi-breads', description: 'Clay tandoor Butter Naan, Garlic Naan, and Tandoori Roti.', image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80', sortOrder: 24, isActive: true },
    { _id: 'cat_pun_25', name: 'Punjabi Parathas', slug: 'punjabi-parathas', description: 'Stuffed parathas with spicy potato, gobi, and paneer fillings.', image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80', sortOrder: 25, isActive: true },
    { _id: 'cat_pun_26', name: 'Punjabi Thali', slug: 'punjabi-thali', description: 'Lavish Punjabi Full Thali and Deluxe Thali platters.', image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80', sortOrder: 26, isActive: true },
    { _id: 'cat_pun_27', name: 'Punjabi Combos', slug: 'punjabi-combos', description: 'Chole Bhature Combo and Paneer Butter Masala Box.', image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80', sortOrder: 27, isActive: true },
    { _id: 'cat_pun_28', name: 'Punjabi Tandoori Specials', slug: 'punjabi-tandoori-specials', description: 'Tandoori Paneer Tikka, Malai Chaap, and Mushroom Tikka.', image: 'https://images.unsplash.com/photo-1567184109411-b28f2700e1e5?auto=format&fit=crop&w=600&q=80', sortOrder: 28, isActive: true },
    { _id: 'cat_pun_29', name: 'Punjabi Desserts', slug: 'punjabi-desserts', description: 'Gulab Jamun, Moong Dal Halwa, and Malpua Rabdi.', image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', sortOrder: 29, isActive: true },
    { _id: 'cat_pun_30', name: 'Punjabi Beverages', slug: 'punjabi-beverages', description: 'Traditional Masala Chai, Badam Milk, and Jaljeera.', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', sortOrder: 30, isActive: true },
    { _id: 'cat_pun_31', name: 'Punjabi Lassi', slug: 'punjabi-lassi', description: 'Thick creamy Sweet Lassi, Mango Lassi, and Rose Lassi.', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', sortOrder: 31, isActive: true },
  ],

  foods: [
    {
      _id: 'food1',
      name: 'Paneer Tikka Angara',
      slug: 'paneer-tikka-angara',
      category: { _id: 'cat1', name: 'Starters & Crisps', slug: 'starters-crisps' },
      description: 'Cottage cheese cubes marinated in Kashmiri red chili, yogurt and roasted gram flour, char-grilled to perfection in clay tandoor.',
      price: 320,
      discountPrice: 280,
      image: 'https://images.unsplash.com/photo-1567184109411-b28f2700e1e5?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'spicy',
      ingredients: ['Fresh Paneer', 'Hung Curd', 'Kashmiri Chili', 'Garam Masala'],
      nutrition: { calories: 380, protein: 18, carbs: 12, fats: 26 },
      preparationTime: 20,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 42,
      tags: ['Tandoori', 'Paneer', 'Chef Special'],
    },
    {
      _id: 'food2',
      name: 'Royal Gujarati Thali Special',
      slug: 'royal-gujarati-thali-special',
      category: { _id: 'cat2', name: 'Gujarati Delights', slug: 'gujarati-delights' },
      description: 'Grand festive thali featuring Ringna No Olo, Gujarati Sweet Kadi, Ringna Bateta Shaak, Dal Fry, Jeera Rice, 4 Phulka Rotis, Farsan, Papad, Pickle and Gulab Jamun.',
      price: 450,
      discountPrice: 399,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Desi Ghee', 'Wheat Flour', 'Jaggery', 'Besan'],
      nutrition: { calories: 850, protein: 22, carbs: 120, fats: 32 },
      preparationTime: 25,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 5.0,
      numReviews: 86,
      tags: ['Grand Thali', 'Kathiyawadi', 'Traditional'],
    },
    {
      _id: 'food3',
      name: 'Paneer Butter Masala',
      slug: 'paneer-butter-masala',
      category: { _id: 'cat3', name: 'Punjabi & North Indian', slug: 'punjabi-north-indian' },
      description: 'Velvety rich tomato and cashew gravy delicately flavored with crushed kasuri methi and finished with generous churns of fresh butter.',
      price: 360,
      discountPrice: 320,
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'medium',
      ingredients: ['Paneer', 'Cashews', 'Fresh Cream', 'Kasuri Methi'],
      nutrition: { calories: 510, protein: 16, carbs: 22, fats: 38 },
      preparationTime: 20,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 110,
      tags: ['Creamy', 'North Indian', 'Most Loved'],
    },
    {
      _id: 'food4',
      name: 'SwadGhar Shahi Veg Dum Biryani',
      slug: 'swadghar-shahi-veg-dum-biryani',
      category: { _id: 'cat4', name: 'Royal Dum Biryani', slug: 'royal-dum-biryani' },
      description: 'Aged Daawat basmati rice layered with garden fresh vegetables, paneer cubes, saffron milk and sealed with dough in a heavy-bottom handi.',
      price: 380,
      discountPrice: 340,
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'medium',
      ingredients: ['Basmati Rice', 'Saffron', 'Mint', 'Fried Onions'],
      nutrition: { calories: 590, protein: 15, carbs: 85, fats: 22 },
      preparationTime: 25,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 95,
      tags: ['Dum Biryani', 'Aromatic'],
    },
    {
      _id: 'food5',
      name: 'Butter Garlic Naan',
      slug: 'butter-garlic-naan',
      category: { _id: 'cat5', name: 'Tandoor & Breads', slug: 'tandoor-breads' },
      description: 'Leavened soft flatbread topped with minced roasted garlic and fresh coriander, brushed with clarified melted butter.',
      price: 85,
      discountPrice: 0,
      image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Flour', 'Garlic', 'Butter', 'Coriander'],
      nutrition: { calories: 190, protein: 5, carbs: 32, fats: 6 },
      preparationTime: 10,
      isAvailable: true,
      isPopular: true,
      isFeatured: false,
      rating: 4.8,
      numReviews: 60,
      tags: ['Clay Tandoor', 'Garlic'],
    },
    {
      _id: 'food6',
      name: 'Gulab Jamun with Rabdi',
      slug: 'gulab-jamun-with-rabdi',
      category: { _id: 'cat7', name: 'Artisanal Desserts', slug: 'artisanal-desserts' },
      description: 'Warm, melt-in-mouth khoya gulab jamuns served atop thick saffron-cardamom rabdi garnished with sliced pistachios and silver vark.',
      price: 180,
      discountPrice: 150,
      image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Khoya', 'Rabdi', 'Saffron', 'Pistachios'],
      nutrition: { calories: 410, protein: 7, carbs: 65, fats: 14 },
      preparationTime: 10,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 5.0,
      numReviews: 120,
      tags: ['Royal Dessert', 'Rabdi'],
    },
    {
      _id: 'food7',
      name: 'Royal Kesariya Mango Lassi',
      slug: 'royal-kesariya-mango-lassi',
      category: { _id: 'cat8', name: 'Beverages & Coolers', slug: 'beverages-coolers' },
      description: 'Thick, creamy yogurt churned with Alphonso mango pulp and infused with Kashmiri saffron strands and crushed almonds.',
      price: 140,
      discountPrice: 120,
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Thick Curd', 'Alphonso Mango', 'Kashmiri Kesar'],
      nutrition: { calories: 280, protein: 7, carbs: 48, fats: 6 },
      preparationTime: 8,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 88,
      tags: ['Mango Lassi', 'Kesar'],
    },
  ],

  coupons: [
    { _id: 'c1', code: 'WELCOME50', discountType: 'percentage', discountValue: 50, minOrderAmount: 200, maxDiscount: 100, expiryDate: new Date(Date.now() + 90 * 86400000), usageLimit: 500, usedCount: 14, description: '50% off up to ₹100 for your first order', isActive: true },
    { _id: 'c2', code: 'SWAD100', discountType: 'fixed', discountValue: 100, minOrderAmount: 499, maxDiscount: 100, expiryDate: new Date(Date.now() + 60 * 86400000), usageLimit: 1000, usedCount: 52, description: 'Flat ₹100 OFF on orders above ₹499', isActive: true },
    { _id: 'c3', code: 'FESTIVE20', discountType: 'percentage', discountValue: 20, minOrderAmount: 350, maxDiscount: 200, expiryDate: new Date(Date.now() + 45 * 86400000), usageLimit: 300, usedCount: 28, description: 'Festive dining treat: 20% discount up to ₹200', isActive: true },
  ],

  orders: [
    {
      _id: 'ord1',
      orderNumber: 'SWAD-2026-8841',
      customer: { _id: '64f1a2b3c4d5e6f7a8b9c0d3', name: 'Aarav Sharma', email: 'customer@gmail.com', phone: '+91 98220 55443' },
      items: [
        { food: 'food2', name: 'Royal Gujarati Thali Special', price: 399, quantity: 2, image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80', foodType: 'veg' },
        { food: 'food7', name: 'Royal Kesariya Mango Lassi', price: 120, quantity: 2, image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=400&q=80', foodType: 'veg' },
      ],
      orderType: 'delivery',
      deliveryAddress: { fullName: 'Aarav Sharma', phone: '+91 98220 55443', address: 'Flat 402, Shivalik High Street', city: 'Ahmedabad', state: 'Gujarat', pincode: '380054' },
      pricing: { subtotal: 1038, discount: 100, tax: 47, deliveryFee: 0, total: 985 },
      couponApplied: { code: 'SWAD100', discountAmount: 100 },
      paymentInfo: { method: 'razorpay', status: 'paid', razorpayOrderId: 'order_rzp_demo123', paidAt: new Date() },
      orderStatus: 'preparing',
      statusHistory: [
        { status: 'pending', timestamp: new Date(Date.now() - 20 * 60000), note: 'Order placed' },
        { status: 'confirmed', timestamp: new Date(Date.now() - 15 * 60000), note: 'Kitchen confirmed' },
        { status: 'preparing', timestamp: new Date(Date.now() - 10 * 60000), note: 'Cooking in tandoor' },
      ],
      estimatedDeliveryTime: new Date(Date.now() + 25 * 60000),
      createdAt: new Date(Date.now() - 20 * 60000),
    },
  ],

  reservations: [
    {
      _id: 'res1',
      customerName: 'Pooja Mehta',
      phone: '+91 98765 44321',
      email: 'pooja@gmail.com',
      date: new Date(Date.now() + 24 * 3600000),
      timeSlot: '07:30 PM',
      guests: 4,
      tableNumber: 'T-06',
      specialRequest: 'Anniversary celebration by window table',
      status: 'confirmed',
      createdAt: new Date(),
    },
  ],

  reviews: [
    {
      _id: 'rev1',
      food: { _id: 'food2', name: 'Royal Gujarati Thali Special', image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80' },
      customer: { name: 'Aarav Sharma', email: 'customer@gmail.com', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80' },
      customerName: 'Aarav Sharma',
      customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
      rating: 5,
      comment: 'Authentic Kathiyawadi flavors, pure desi ghee aroma and hot phulkas. 10/10!',
      isApproved: true,
      createdAt: new Date(),
    },
  ],

  settings: {
    restaurantName: 'SwadGhar Fine Dining & Delicacies',
    tagline: 'A Tradition of Authentic Royal Flavors & Warm Hospitality',
    email: 'contact@swadghar.com',
    phone: '+91 98765 43210',
    address: { street: '104 Heritage Boulevard, Ring Road', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015', country: 'India' },
    financial: { taxRatePercentage: 5, deliveryFee: 40, freeDeliveryThreshold: 499, minOrderAmount: 150 },
    isOnlineOrderingOpen: true,
    isTableBookingOpen: true,
  },
};

module.exports = mockStore;
