// In-Memory Database Fallback Store for Development Mode
const bcrypt = require('bcryptjs');

const mockStore = {
  users: [
    {
      _id: '64f1a2b3c4d5e6f7a8b9c0d1',
      name: 'SwadGhar Admin',
      email: 'admin@swadghar.com',
      passwordHash: '$2a$10$wO3bS9R8J7C8gqH8yDqSSe3X4p6V7A9C2m1P3L4k5J6H7G8F9E0D1', // Admin@123
      phone: '+91 98980 12345',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      addresses: [{ _id: 'addr1', street: 'Admin Quarters', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015', isDefault: true }],
      isBlocked: false,
      createdAt: new Date(),
    },
    {
      _id: '64f1a2b3c4d5e6f7a8b9c0d2',
      name: 'Ramesh Patel (Staff)',
      email: 'staff@swadghar.com',
      passwordHash: '$2a$10$wO3bS9R8J7C8gqH8yDqSSe3X4p6V7A9C2m1P3L4k5J6H7G8F9E0D1', // Staff@123
      phone: '+91 98765 11223',
      role: 'staff',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      addresses: [],
      isBlocked: false,
      createdAt: new Date(),
    },
    {
      _id: '64f1a2b3c4d5e6f7a8b9c0d3',
      name: 'Aarav Sharma',
      email: 'customer@gmail.com',
      passwordHash: '$2a$10$wO3bS9R8J7C8gqH8yDqSSe3X4p6V7A9C2m1P3L4k5J6H7G8F9E0D1', // Customer@123
      phone: '+91 98220 55443',
      role: 'customer',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      addresses: [{ _id: 'addr2', street: 'Flat 402, Shivalik High Street', city: 'Ahmedabad', state: 'Gujarat', pincode: '380054', landmark: 'Opposite Central Park', isDefault: true }],
      isBlocked: false,
      createdAt: new Date(),
    },
  ],

  categories: [
    { _id: 'cat1', name: 'Starters & Crisps', slug: 'starters-crisps', description: 'Crispy, flavorful appetizers to ignite your palate.', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', sortOrder: 1, isActive: true },
    { _id: 'cat2', name: 'Gujarati Delights', slug: 'gujarati-delights', description: 'Authentic Kathiyawadi and traditional Gujarati heritage recipes.', image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80', sortOrder: 2, isActive: true },
    { _id: 'cat3', name: 'Punjabi & North Indian', slug: 'punjabi-north-indian', description: 'Rich creamy gravies infused with slow-simmered spices and desi ghee.', image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80', sortOrder: 3, isActive: true },
    { _id: 'cat4', name: 'Royal Dum Biryani', slug: 'royal-dum-biryani', description: 'Long-grain basmati infused with saffron, caramelized onions and herbs.', image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80', sortOrder: 4, isActive: true },
    { _id: 'cat5', name: 'Tandoor & Breads', slug: 'tandoor-breads', description: 'Clay-oven fired naans, rotis, and succulent tikkas.', image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80', sortOrder: 5, isActive: true },
    { _id: 'cat6', name: 'Indo-Chinese', slug: 'indo-chinese', description: 'Wok-tossed noodles, manchurians, and fiery schezwan delicacies.', image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80', sortOrder: 6, isActive: true },
    { _id: 'cat7', name: 'Artisanal Desserts', slug: 'artisanal-desserts', description: 'Sweet sinful pleasures crafted from condensed milk, saffron and pistachios.', image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', sortOrder: 7, isActive: true },
    { _id: 'cat8', name: 'Beverages & Coolers', slug: 'beverages-coolers', description: 'Thirst-quenching lassis, mocktails and traditional cooling drinks.', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', sortOrder: 8, isActive: true },
  ],

  foods: [
    {
      _id: 'food1',
      name: 'Paneer Tikka Angara',
      slug: 'paneer-tikka-angara',
      category: { _id: 'cat1', name: 'Starters & Crisps', slug: 'starters-crisps' },
      description: 'Cottage cheese cubes marinated in Kashmiri red chili, yogurt and roasted gram flour, char-grilled to perfection in clay tandoor.',
      price: 320,
      discountPrice: 280,
      image: 'https://images.unsplash.com/photo-1567184109411-b28f2700e1e5?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'spicy',
      ingredients: ['Fresh Paneer', 'Hung Curd', 'Kashmiri Chili', 'Garam Masala'],
      nutrition: { calories: 380, protein: 18, carbs: 12, fats: 26 },
      preparationTime: 20,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 42,
      tags: ['Tandoori', 'Paneer', 'Chef Special'],
    },
    {
      _id: 'food2',
      name: 'Royal Gujarati Thali Special',
      slug: 'royal-gujarati-thali-special',
      category: { _id: 'cat2', name: 'Gujarati Delights', slug: 'gujarati-delights' },
      description: 'Grand festive thali featuring Ringna No Olo, Gujarati Sweet Kadi, Ringna Bateta Shaak, Dal Fry, Jeera Rice, 4 Phulka Rotis, Farsan, Papad, Pickle and Gulab Jamun.',
      price: 450,
      discountPrice: 399,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Desi Ghee', 'Wheat Flour', 'Jaggery', 'Besan'],
      nutrition: { calories: 850, protein: 22, carbs: 120, fats: 32 },
      preparationTime: 25,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 5.0,
      numReviews: 86,
      tags: ['Grand Thali', 'Kathiyawadi', 'Traditional'],
    },
    {
      _id: 'food3',
      name: 'Paneer Butter Masala',
      slug: 'paneer-butter-masala',
      category: { _id: 'cat3', name: 'Punjabi & North Indian', slug: 'punjabi-north-indian' },
      description: 'Velvety rich tomato and cashew gravy delicately flavored with crushed kasuri methi and finished with generous churns of fresh butter.',
      price: 360,
      discountPrice: 320,
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'medium',
      ingredients: ['Paneer', 'Cashews', 'Fresh Cream', 'Kasuri Methi'],
      nutrition: { calories: 510, protein: 16, carbs: 22, fats: 38 },
      preparationTime: 20,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 110,
      tags: ['Creamy', 'North Indian', 'Most Loved'],
    },
    {
      _id: 'food4',
      name: 'SwadGhar Shahi Veg Dum Biryani',
      slug: 'swadghar-shahi-veg-dum-biryani',
      category: { _id: 'cat4', name: 'Royal Dum Biryani', slug: 'royal-dum-biryani' },
      description: 'Aged Daawat basmati rice layered with garden fresh vegetables, paneer cubes, saffron milk and sealed with dough in a heavy-bottom handi.',
      price: 380,
      discountPrice: 340,
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'medium',
      ingredients: ['Basmati Rice', 'Saffron', 'Mint', 'Fried Onions'],
      nutrition: { calories: 590, protein: 15, carbs: 85, fats: 22 },
      preparationTime: 25,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 95,
      tags: ['Dum Biryani', 'Aromatic'],
    },
    {
      _id: 'food5',
      name: 'Butter Garlic Naan',
      slug: 'butter-garlic-naan',
      category: { _id: 'cat5', name: 'Tandoor & Breads', slug: 'tandoor-breads' },
      description: 'Leavened soft flatbread topped with minced roasted garlic and fresh coriander, brushed with clarified melted butter.',
      price: 85,
      discountPrice: 0,
      image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Flour', 'Garlic', 'Butter', 'Coriander'],
      nutrition: { calories: 190, protein: 5, carbs: 32, fats: 6 },
      preparationTime: 10,
      isAvailable: true,
      isPopular: true,
      isFeatured: false,
      rating: 4.8,
      numReviews: 60,
      tags: ['Clay Tandoor', 'Garlic'],
    },
    {
      _id: 'food6',
      name: 'Gulab Jamun with Rabdi',
      slug: 'gulab-jamun-with-rabdi',
      category: { _id: 'cat7', name: 'Artisanal Desserts', slug: 'artisanal-desserts' },
      description: 'Warm, melt-in-mouth khoya gulab jamuns served atop thick saffron-cardamom rabdi garnished with sliced pistachios and silver vark.',
      price: 180,
      discountPrice: 150,
      image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Khoya', 'Rabdi', 'Saffron', 'Pistachios'],
      nutrition: { calories: 410, protein: 7, carbs: 65, fats: 14 },
      preparationTime: 10,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 5.0,
      numReviews: 120,
      tags: ['Royal Dessert', 'Rabdi'],
    },
    {
      _id: 'food7',
      name: 'Royal Kesariya Mango Lassi',
      slug: 'royal-kesariya-mango-lassi',
      category: { _id: 'cat8', name: 'Beverages & Coolers', slug: 'beverages-coolers' },
      description: 'Thick, creamy yogurt churned with Alphonso mango pulp and infused with Kashmiri saffron strands and crushed almonds.',
      price: 140,
      discountPrice: 120,
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
      foodType: 'veg',
      spiceLevel: 'mild',
      ingredients: ['Thick Curd', 'Alphonso Mango', 'Kashmiri Kesar'],
      nutrition: { calories: 280, protein: 7, carbs: 48, fats: 6 },
      preparationTime: 8,
      isAvailable: true,
      isPopular: true,
      isFeatured: true,
      rating: 4.9,
      numReviews: 88,
      tags: ['Mango Lassi', 'Kesar'],
    },
  ],

  coupons: [
    { _id: 'c1', code: 'WELCOME50', discountType: 'percentage', discountValue: 50, minOrderAmount: 200, maxDiscount: 100, expiryDate: new Date(Date.now() + 90 * 86400000), usageLimit: 500, usedCount: 14, description: '50% off up to ₹100 for your first order', isActive: true },
    { _id: 'c2', code: 'SWAD100', discountType: 'fixed', discountValue: 100, minOrderAmount: 499, maxDiscount: 100, expiryDate: new Date(Date.now() + 60 * 86400000), usageLimit: 1000, usedCount: 52, description: 'Flat ₹100 OFF on orders above ₹499', isActive: true },
    { _id: 'c3', code: 'FESTIVE20', discountType: 'percentage', discountValue: 20, minOrderAmount: 350, maxDiscount: 200, expiryDate: new Date(Date.now() + 45 * 86400000), usageLimit: 300, usedCount: 28, description: 'Festive dining treat: 20% discount up to ₹200', isActive: true },
  ],

  orders: [
    {
      _id: 'ord1',
      orderNumber: 'SWAD-2026-8841',
      customer: { _id: '64f1a2b3c4d5e6f7a8b9c0d3', name: 'Aarav Sharma', email: 'customer@gmail.com', phone: '+91 98220 55443' },
      items: [
        { food: 'food2', name: 'Royal Gujarati Thali Special', price: 399, quantity: 2, image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80', foodType: 'veg' },
        { food: 'food7', name: 'Royal Kesariya Mango Lassi', price: 120, quantity: 2, image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=400&q=80', foodType: 'veg' },
      ],
      orderType: 'delivery',
      deliveryAddress: { fullName: 'Aarav Sharma', phone: '+91 98220 55443', address: 'Flat 402, Shivalik High Street', city: 'Ahmedabad', state: 'Gujarat', pincode: '380054' },
      pricing: { subtotal: 1038, discount: 100, tax: 47, deliveryFee: 0, total: 985 },
      couponApplied: { code: 'SWAD100', discountAmount: 100 },
      paymentInfo: { method: 'razorpay', status: 'paid', razorpayOrderId: 'order_rzp_demo123', paidAt: new Date() },
      orderStatus: 'preparing',
      statusHistory: [
        { status: 'pending', timestamp: new Date(Date.now() - 20 * 60000), note: 'Order placed' },
        { status: 'confirmed', timestamp: new Date(Date.now() - 15 * 60000), note: 'Kitchen confirmed' },
        { status: 'preparing', timestamp: new Date(Date.now() - 10 * 60000), note: 'Cooking in tandoor' },
      ],
      estimatedDeliveryTime: new Date(Date.now() + 25 * 60000),
      createdAt: new Date(Date.now() - 20 * 60000),
    },
  ],

  reservations: [
    {
      _id: 'res1',
      customerName: 'Pooja Mehta',
      phone: '+91 98765 44321',
      email: 'pooja@gmail.com',
      date: new Date(Date.now() + 24 * 3600000),
      timeSlot: '07:30 PM',
      guests: 4,
      tableNumber: 'T-06',
      specialRequest: 'Anniversary celebration by window table',
      status: 'confirmed',
      createdAt: new Date(),
    },
  ],

  reviews: [
    {
      _id: 'rev1',
      food: { _id: 'food2', name: 'Royal Gujarati Thali Special', image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80' },
      customer: { name: 'Aarav Sharma', email: 'customer@gmail.com', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80' },
      customerName: 'Aarav Sharma',
      customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
      rating: 5,
      comment: 'Authentic Kathiyawadi flavors, pure desi ghee aroma and hot phulkas. 10/10!',
      isApproved: true,
      createdAt: new Date(),
    },
  ],

  settings: {
    restaurantName: 'SwadGhar Fine Dining & Delicacies',
    tagline: 'A Tradition of Authentic Royal Flavors & Warm Hospitality',
    email: 'contact@swadghar.com',
    phone: '+91 98765 43210',
    address: { street: '104 Heritage Boulevard, Ring Road', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015', country: 'India' },
    financial: { taxRatePercentage: 5, deliveryFee: 40, freeDeliveryThreshold: 499, minOrderAmount: 150 },
    isOnlineOrderingOpen: true,
    isTableBookingOpen: true,
  },
};

module.exports = mockStore;
